export { default as Login } from './Login';
export { default as Signup } from './SignupForm';
export { default as Profile } from './Profile';
export { default as PickQuestion } from './PickQuestion';
export { default as EditProfile } from './EditProfile';
export { default as Quiz } from './Quiz'
export { default as Waiting } from './Waiting';
export { default as Answer } from './Answer';
export { default as Random } from './Random';